### ISSUE TITLE
Analyse des besoins du systèmes

### ISSUE THREAD

**Issue by msesboue** [msesboue/projet_bd_avancees#2]
Résumer les besoins du système afin de faire les choix d'architecture :

- quelles informations nous fourni l'utilisateur ?
- quelles information nous avons ? --> données spatiales des pistes cyclables + restaurants. 
- De quels informations sur les restaurants avons nous besoin ?
- Quelles requêtes fais l'utilisateur ?
- Quelles resultats doit-on fournir ?
- Quels calculs cela implique ?

**Comment by MartinSass5** [comment]
Bonjour
Voici mon texte. Il est un peu long (je ne voulais rien manqué) mais il peut aussi servir pour introduire les autres sections. Nous ferons la composition finale pour tenir sur 1 page tel que demandé dans le livrable quand nous aurons tous les morceaux.
Vous pouvez me donner vos commentaires ou on en rediscute mardi prochain après le cours.
Ciao
[Livrable 1 - Besoins du système.docx](https://github.com/msesboue/projet_bd_avancees/files/3626829/Livrable.1.-.Besoins.du.systeme.docx)
